# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 16 Nov 2015 23:02:21 +0000
*               @ALL          1
*               @user         8
