<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: codywarmbo
 * Date: Tue, 17 Nov 2015 02:16:07 -0800
 */

$conf['title'] = 'CPCE Wiki';
$conf['template'] = 'bootstrap3';
$conf['license'] = 'cc-by-sa';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['showuseras'] = 'username';
$conf['useacl'] = 1;
$conf['autopasswd'] = 0;
$conf['superuser'] = '@admin';
$conf['proxy']['user'] = 'codywarmbo';
$conf['proxy']['pass'] = '<b>VGhlZGF5czAwIQ==';
$conf['plugin']['smtp']['smtp_host'] = 'smtp.gmail.com.';
$conf['plugin']['smtp']['smtp_ssl'] = 'tls';
$conf['plugin']['smtp']['auth_user'] = 'admin@cpcenth.net';
$conf['plugin']['wrap']['darkTpl'] = 1;
$conf['tpl']['bootstrap3']['bootstrapTheme'] = 'bootswatch';
$conf['tpl']['bootstrap3']['bootswatchTheme'] = 'yeti';
$conf['tpl']['bootstrap3']['fixedTopNavbar'] = 1;
$conf['tpl']['bootstrap3']['fluidContainer'] = 1;
$conf['tpl']['bootstrap3']['showPageTools'] = 'logged';
$conf['tpl']['bootstrap3']['showBadges'] = 0;
$conf['tpl']['bootstrap3']['showLoginOnFooter'] = 1;
$conf['tpl']['bootstrap3']['useGravatar'] = 1;

// end auto-generated content
